import Head from 'next/head'
import Image from 'next/image'
import '../styles/Home.module.css'
import React, {useState, useEffect} from 'react'
import { getArticles } from '../bundle/utils/request'
import HeaderComponent from '../bundle/components/header_component'
import HeaderMenu from '../bundle/components/header_menu'

export default function Home() {

  //creating the variable which holds all the articles taken from the  News API
  const [articles, setArticles] = useState({});

  //Using the useEffect Hook to populate the articles data
  useEffect(() => {
    setArticles(getArticles());
  },[]);



  //checking that the articles are visible on the devtools
  console.log(articles)
  return (
    <div>
      <Head>
        <title>News API | SmartCode</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Dosis:wght@200;300;400;500&display=swap" rel="stylesheet"></link>
      </Head>

      <HeaderComponent />
      <HeaderMenu />
      <footer>
        
          Crafted by @andreas
          
      </footer>
    </div>
  )
}


